title: "CNS 2018 workshop: How does learning reshape dimensionality of collective network activity?"
theme: jekyll-theme-slate
description: "July 18th 2018 (during CNS 2018), Seattle"
github:
is_project_page: true
